apiVersion: flinkoperator.k8s.io/v1beta1
kind: FlinkCluster
metadata:
  name: flink-on-k8s-cluster
spec:
  image:
    name: flink:1.8.1
  jobManager:
    resources:
      limits:
        memory: "1Gi"
  taskManager:
    replicas: 2
    resources:
      limits:
        memory: "2Gi"
    sidecars:
      - name: beam-worker-pool
        image: apache/beam_python3.7_sdk:2.23.0
        imagePullPolicy: Always
        args: ["--worker_pool"]
  flinkProperties:
    taskmanager.numberOfTaskSlots: "1"
